AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'

Layout/CaseIndentation:
  EnforcedStyle: end

Lint/RescueException:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SignalException:
  Exclude:
    - 'lib/redis/connection/synchrony.rb'

Style/StringLiterals:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Lint/NonLocalExitFromIterator:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/ElseAlignment:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - lib/redis/connection/ruby.rb

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'test/**/*'

Style/SoleNestedConditional:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/StderrPuts:
  Enabled: false
